### ISSUE TITLE
레이블 삭제해도 이미 작성된 이슈에 적용된 레이블이 사라지지 않는 현상

### ISSUE THREAD

**Issue by eeeesong** [d-h-k/issue-tracker#104]
레이블 수정 시엔 기존 이슈 반영이 되는데 삭제하는 경우엔 반영이 되지 않는 것 같습니다!

**Comment by eeeesong** [comment]
@Jiwon-JJW 혹시나 시간이 되신다면 확인 부탁드려요 :)

**Comment by Jiwon-JJW** [comment]
해결 했습니다!!!

**Comment by eeeesong** [comment]
오 혹시 너무 바쁘실까 싶어서 여기다만 남긴건데
빠르게 해결해주셔서 감사합니다!
이슈는 닫아보도록 하겠습니다👍🏻
