### ISSUE TITLE
[iOS] github 소셜로그인 (OAuth)

### ISSUE THREAD

**Issue by eeeesong** [d-h-k/issue-tracker#21]
- [x] : Github으로 토큰받기.
- [x] : Keychain을 이용해서 보안을 높여보기
- [x] : 알라모파이어 이용해보기.

**Comment by JacksonPk** [comment]
옛썰!

**Comment by eeeesong** [comment]
## `jwt 유효성` 확인 관련 논의 

### SceneDelegate vs. IssueTrackerTabBarController

`SceneDelegate`
- 장점: 이미 VC 띄우는 코드들이 있으므로 중복 작성을 하지 않아도 된다
- 단점: 빈 화면 위에 alert가 뜨게 될 것이다? -> 로그인 창을 띄우고 alert를 띄우면 되긴 하지만...?

`IssueTrackerTabBarController`
- 장점: 빈 이슈 화면이라도 본 채로 alert를 띄우게 된다
- 단점: 로그인 VC 생성 코드를 한번 더 써야 한다

-> SceneDelegate에서 하기로 결정
