### ISSUE TITLE
[iOS] 소셜로그인 합병작업

### ISSUE THREAD

**Issue by JacksonPk** [d-h-k/issue-tracker#32]
- [x] : Apple,Github 로그인 합병 (1차 머지)
- [x] : 중복 인터페이스 합병 
- [x] : Native KeyChain 사용
- [x] : SceneDelegate에서 로그인 정보 확인
- [x] : TabBarViewControllerInfo에 필요한 정보추가(롤로와 협의해서 더 좋은 방안을 의논해보고 수정하기)

      탭바 Item의 계정Image를 제외하고는 모두 systemName으로 사용
      isAccountImage를 사용해 계정탭바에서는 avartarURL을 전달해줌
      Apple에서는 avartarURL이 존재하지 않으므로 대신 UIImage(systemName: "person.circle")으로 대체하기.

해당 코드
```swift
private struct TabBarViewControllerInfo {
        let title: String
        let image: UIImage?
        let isAccountImage: Bool
        let type: UIViewController.Type
        
        init(title: String, imageName: String, isAccountImage: Bool, type: UIViewController.Type) {
            self.title = title
            self.type = type
            self.isAccountImage = isAccountImage
            
            if self.isAccountImage {
                //Apple에서는 계정이미지가 없기때문에 "person.circle" 넣는다.
                guard let url = URL(string: imageName) else {
                    self.image = UIImage(systemName: "person.circle")
                    return
                }
                let imagedata = try? Data(contentsOf: url)
                self.image = UIImage(data: imagedata!)!.resizedImage(size: CGSize(width: 19.666, height: 19.0))
                
            }else {
                self.image = UIImage(systemName: "person.circle")
            }
        }
    }
```

- [x] jwt 만료 확인

**Comment by eeeesong** [comment]
탭바 생성하는 모듈을 따로 분리해두었습니다! 
이미지 추가 관련해서는 이미지 다운로드 받는 모듈을 추가하고 탭바 컨트롤러에서 url이 있을 경우 다운받아서 채우도록 적어놨는데
잭슨이 겪으신 문제처럼 바로 추가가 안돼서.. 차차 같이 해결해보면 좋을 것 같아요

https://iosrevisited.blogspot.com/2019/08/add-imageview-profile-picture-to-tabbar-swift-ios.html

위의 링크처럼 다소 복잡한 것 같네요ㅎㅎㅎ...
