### ISSUE TITLE
[iOS] 소셜로그인 이미지 사이즈 버그

### ISSUE THREAD

**Issue by JacksonPk** [d-h-k/issue-tracker#35]
## 버그 : AvartarURL로 가져온 데이터의 크기가 이상하게 작용되는 현상.

해당 URL :  https://avatars.githubusercontent.com/u/52390975?v=4

### 1. 460x460처리 되고 실제로는 이미지가 보이질 않음.

<img width="1106" alt="Screen Shot 2021-06-10 at 6 26 46 PM" src="https://user-images.githubusercontent.com/52390975/121500996-c307e600-ca19-11eb-9069-6743f054d01f.png">

### 2. custom UIImage resizedImage()를 사용시 원하는만큼 이미지가 작아졌으나 거의 보이질 않음.

<img width="1108" alt="Screen Shot 2021-06-10 at 6 28 42 PM" src="https://user-images.githubusercontent.com/52390975/121501305-10845300-ca1a-11eb-86cb-ea295cdf9072.png">

## 해결
하드코딩을 통해 사이즈를 조절했다.

**Comment by eeeesong** [comment]
https://iosrevisited.blogspot.com/2019/08/add-imageview-profile-picture-to-tabbar-swift-ios.html

**Comment by JacksonPk** [comment]
추후에 updateUserImage()가 사용되는 곳은 ```MyAccountViewController``` 에서 사용되므로  ```IssueTrackerTabBarController```에 있는 프로토콜을 ```MyAccountViewController``` 로 넘겨도 되지 않을까 생각이 듭니다.

**Comment by JacksonPk** [comment]
다시보니 
``` swift 
private func updateUserImage() {
        guard let imageURL = self.loginInfo?.avatarURL,
              let viewControllers = self.viewControllers,
              let myAccountViewController = viewControllers.compactMap({ $0 as? MyAccountViewController }).first else { return }
        
        imageLoadManager.load(from: imageURL) { cachePath in
            guard let userImage = UIImage(contentsOfFile: cachePath),
                  let iconSize = myAccountViewController.tabBarItem.image?.size else { return }
            
            let resizedUserImage = userImage.resizedImage(size: iconSize)
            
            DispatchQueue.main.async {
                myAccountViewController.tabBarItem.image = resizedUserImage
            }
        }
    }
```
가 ```MyAccountViewController``` 에만 적용되는 것으로 보입니다.
그러면 총 4번이 불리는것인가 확인을 하고 있습니다.

**Comment by JacksonPk** [comment]
``` swift 
let myAccountViewController = viewControllers.compactMap({ $0 as? MyAccountViewController }).first else { return }
```
디버그를 하니 4개의 viewControllers에서 myAccountViewController를 찾으려고 하나 모두 return으로 되는 현상이 발견 되었습니다.
수정해봐야할 것 같습니다.

**Comment by JacksonPk** [comment]
현재 IssueTrackerTabBarCreator 쪽으로 updateUserImage()를 이동시켰습니다.

**Comment by JacksonPk** [comment]
<img src =https://user-images.githubusercontent.com/52390975/121872681-85200000-cd40-11eb-956b-9f1687275d8a.png width = 200>

구현은 되었는데 사이즈가 이상합니다.
