### ISSUE TITLE
[iOS] 컬러 에셋 대소문자 변경 미반영 문제

### ISSUE THREAD

**Issue by eeeesong** [d-h-k/issue-tracker#93]

**Comment by eeeesong** [comment]
@JacksonPk 지난번 수정 때 같이 본 문젠데, 지금 보니까 또 반영이 안되어 있어서 한번 더 고쳤습니다!
대소문자만 변경할 경우 git add할 대상으로 잡히지 않을 때가 있는 것 같아요
지난번에도 비슷한 문제가 있어서 도움을 구한 적이 있는데,
아예 다른 이름으로 한번 바꿔서 커밋한다음에 다시 그 이름으로 바꾸면 정상 반영 된다는 걸 찾아서 이번에도 그렇게 변경했습니다!

**Comment by JacksonPk** [comment]
저도 iOS/dev 받을 때 또 그렇게 된거같은데 이제는 됐지 않았을까 싶네요.
감사합니다!!

**Comment by eeeesong** [comment]
네엡!! 그럼 이슈는 닫겠습니다
